version: '3.8'

networks:
  appnet:
    driver: bridge

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PGUSER:-app}
      - POSTGRES_PASSWORD=${PGPASSWORD:-password}
      - POSTGRES_DB=${PGDATABASE:-app}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  backend:
    image: is3-backend:${BACKEND_TAG:-prod}
    environment:
      - ENV=production
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL:-postgres://app:password@db:5432/app?sslmode=disable}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5432}
      - PGUSER=${PGUSER:-app}
      - PGPASSWORD=${PGPASSWORD:-password}
      - PGDATABASE=${PGDATABASE:-app}
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "8000:8000"

  frontend:
    image: is3-frontend:${FRONTEND_TAG:-prod}
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - INTERNAL_API=${INTERNAL_API:-http://backend:8000}
    depends_on:
      - backend
    networks:
      - appnet
    ports:
      - "3000:3000"

volumes:
  db_data_prod:
